trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

schedules:
  - cron: "0 0 * * *"
    displayName: Nightly
    always: true
    branches:
      include:
        - devel
        - stable-*

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.5.0

pool: Standard

stages:
  - template: grouped.yml
    parameters:
      stage: Sanity
      targets:
        - name: Test
          test: sanity
      groups:
        - 1
        - 2
        - 3
        - 4
        - 5
  - template: grouped.yml
    parameters:
      stage: Units
      targets:
        - name: Python
          test: units
      groups:
        - 2.6
        - 2.7
        - 3.5
        - 3.6
        - 3.7
        - 3.8
        - 3.9
  - template: ungrouped.yml
    parameters:
      stage: Windows
      targets:
        - name: 2012
          test: windows/2012
        - name: 2012-R2
          test: windows/2012-R2
        - name: 2016
          test: windows/2016
        - name: 2019
          test: windows/2019
  - template: grouped.yml
    parameters:
      stage: Remote
      nameFormat: "{0} - {1}"
      targets:
        - name: macOS 10.15
          test: macos/10.15
        - name: RHEL 7.8
          test: rhel/7.8
        - name: RHEL 8.2
          test: rhel/8.2
        - name: FreeBSD 11.1
          test: freebsd/11.1
        - name: FreeBSD 12.1
          test: freebsd/12.1
      groups:
        - 1
        - 2
        - 3
        - 4
        - 5
  - template: grouped.yml
    parameters:
      stage: Docker
      nameFormat: "{0} - {1}"
      targets:
        - name: Alpine 3
          test: linux/alpine3
        - name: CentOS 6
          test: linux/centos6
        - name: CentOS 7
          test: linux/centos7
        - name: CentOS 8
          test: linux/centos8
        - name: Fedora 31
          test: linux/fedora31
        - name: Fedora 32
          test: linux/fedora32
        - name: openSUSE 15 py2
          test: linux/opensuse15py2
        - name: openSUSE 15 py3
          test: linux/opensuse15
        - name: Ubuntu 16.04
          test: linux/ubuntu1604
        - name: Ubuntu 18.04
          test: linux/ubuntu1804
      groups:
        - 1
        - 2
        - 3
        - 4
        - 5
  - template: grouped.yml
    parameters:
      stage: Galaxy
      targets:
        - name: Python
          test: galaxy
      groups:
        - 2.7
        - 3.6
  - template: grouped.yml
    parameters:
      stage: Generic
      targets:
        - name: Python
          test: generic
      groups:
        - 2.7
        - 3.6
  - template: ungrouped.yml
    parameters:
      stage: Incidental
      targets:
        - name: OS X 10.11
          test: i/osx/10.11
        - name: RHEL 7.8
          test: i/rhel/7.8
        - name: RHEL 8.2
          test: i/rhel/8.2
        - name: FreeBSD 11.1
          test: i/freebsd/11.1
        - name: FreeBSD 12.1
          test: i/freebsd/12.1
        - name: CentOS 6
          test: i/linux/centos6
        - name: CentOS 7
          test: i/linux/centos7
        - name: CentOS 8
          test: i/linux/centos8
        - name: Fedora 31
          test: i/linux/fedora31
        - name: Fedora 32
          test: i/linux/fedora32
        - name: openSUSE 15 py2
          test: i/linux/opensuse15py2
        - name: openSUSE 15 py3
          test: i/linux/opensuse15
        - name: Ubuntu 16.04
          test: i/linux/ubuntu1604
        - name: Ubuntu 18.04
          test: i/linux/ubuntu1804
        - name: Windows 2012
          test: i/windows/2012
        - name: Windows 2012-R2
          test: i/windows/2012-R2
        - name: Windows 2016
          test: i/windows/2016
        - name: Windows 2019
          test: i/windows/2019
        - name: IOS csr1000v
          test: i/ios/csr1000v///
        - name: VyOS Python 2.7
          test: i/vyos/1.1.8/2.7
        - name: VyOS Python 3.6
          test: i/vyos/1.1.8/3.6
        - name: AWS Python 2.7
          test: i/aws/2.7
        - name: AWS Python 3.6
          test: i/aws/3.6
        - name: Cloud
          test: i/cloud///
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity
      - Units
      - Windows
      - Remote
      - Docker
      - Galaxy
      - Generic
      - Incidental
    jobs:
      - template: coverage.yml
