trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.5.0

pool: Standard

stages:
  - template: grouped.yml
    parameters:
      stage: Docker
      nameFormat: "{0} - {1}"
      targets:
        - name: Fedora 33
          test: linux/fedora33
      groups:
        - 2
